"use strict";
const http=require("http"),fs=require("fs"),path=require("path");const {WebSocketServer}=require("ws");
const PORT=Number(process.env.PORT||8080),SHOP_KEY=String(process.env.SHOP_KEY||"CHANGE_ME");
const LINE_TOKEN=String(process.env.LINE_CHANNEL_ACCESS_TOKEN||""),LINE_TO=String(process.env.LINE_TO||""),DAILY_HOUR=Number(process.env.DAILY_SUMMARY_HOUR||21);
const ROOT=__dirname,DATA=path.join(ROOT,"data");fs.mkdirSync(DATA,{recursive:true});const ORDERS=path.join(DATA,"cloud-orders.json"),AUDIT=path.join(DATA,"cloud-audit.json"),BACKUP=path.join(DATA,"latest-backup.json"),LINE_STATE=path.join(DATA,"line-state.json");
const load=f=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch(e){return []}},save=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
function json(res,c,o){res.writeHead(c,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type,X-Shop-Key,X-Dashboard-Token","Access-Control-Allow-Methods":"GET,POST,OPTIONS"});res.end(JSON.stringify(o))}
function body(req){return new Promise((ok,no)=>{let s="";req.on("data",d=>{s+=d;if(s.length>15e6)req.destroy()});req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on("error",no)})}
const shop=req=>SHOP_KEY!=="CHANGE_ME"&&req.headers["x-shop-key"]===SHOP_KEY;
function bkkParts(d=new Date()){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d);return Object.fromEntries(p.map(x=>[x.type,x.value]))}
function dateKey(d=new Date()){const p=bkkParts(d);return `${p.year}-${p.month}-${p.day}`}
function keyToUTC(k){const [y,m,d]=k.split('-').map(Number);return new Date(Date.UTC(y,m-1,d,-7,0,0))}function addDays(k,n){const d=keyToUTC(k);d.setUTCDate(d.getUTCDate()+n);return dateKey(d)}
function rangeFor(type,anchor=dateKey()){let start,end;if(type==='today'){start=anchor;end=addDays(anchor,1)}else if(type==='week'){start=addDays(anchor,-6);end=addDays(anchor,1)}else if(type==='month'){const [y,m]=anchor.split('-').map(Number);start=`${y}-${String(m).padStart(2,'0')}-01`;end=m===12?`${y+1}-01-01`:`${y}-${String(m+1).padStart(2,'0')}-01`}else{const y=Number(anchor.slice(0,4));start=`${y}-01-01`;end=`${y+1}-01-01`}return {start,end}}
function aggregate(rows,start,end){const all=rows.filter(o=>{const k=o.orderDate||dateKey(new Date(o.time));return k>=start&&k<end}),paid=all.filter(o=>o.status!=="cancelled");const revenue=paid.reduce((s,o)=>s+Number(o.total||0),0),cash=paid.filter(o=>o.payment==="เงินสด").reduce((s,o)=>s+Number(o.total||0),0),qr=paid.filter(o=>o.payment==="QR").reduce((s,o)=>s+Number(o.total||0),0);const prod={};paid.forEach(o=>(o.items||[]).forEach(i=>prod[i.name]=(prod[i.name]||0)+Number(i.qty||0)));const topProducts=Object.entries(prod).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,qty])=>({name,qty}));return {start,end,orders:paid.length,cancelled:all.length-paid.length,revenue,cash,qr,average:paid.length?revenue/paid.length:0,topProducts,lastOrder:paid.slice().sort((a,b)=>new Date(b.time)-new Date(a.time))[0]||null}}
const clients=new Set();function broadcast(x){const t=JSON.stringify(x);for(const ws of clients)if(ws.readyState===1)ws.send(t)}
async function linePush(text){if(!LINE_TOKEN||!LINE_TO)return {ok:false,reason:"not_configured"};const r=await fetch("https://api.line.me/v2/bot/message/push",{method:"POST",headers:{Authorization:`Bearer ${LINE_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({to:LINE_TO,messages:[{type:"text",text}]})});return {ok:r.ok,status:r.status}}
function dailyText(){const rows=load(ORDERS),k=dateKey(),{start,end}=rangeFor('today',k),s=aggregate(rows,start,end),top=s.topProducts[0];return `📊 สรุปยอดขาย ${k}\nออเดอร์: ${s.orders}\nยอดขาย: ฿${s.revenue.toLocaleString()}\n💵 เงินสด: ฿${s.cash.toLocaleString()}\n📱 QR: ฿${s.qr.toLocaleString()}\nเฉลี่ย/บิล: ฿${Math.round(s.average).toLocaleString()}\nขายดีที่สุด: ${top?`${top.name} × ${top.qty}`:'—'}\n❌ ยกเลิก: ${s.cancelled}`}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,"http://localhost");if(req.method==="OPTIONS")return json(res,204,{});
 if(u.pathname==="/api/orders/sync"&&req.method==="POST"){if(!shop(req))return json(res,401,{error:"unauthorized"});try{const b=await body(req),o=b.order;if(!o||o.id==null)return json(res,400,{error:"missing order"});const rows=load(ORDERS),clean={id:o.id,number:o.number,total:Number(o.total||0),payment:o.payment||"-",status:o.status||"paid",time:o.time||new Date().toISOString(),orderDate:o.orderDate||dateKey(new Date(o.time)),staffName:o.staffName||"",items:Array.isArray(o.items)?o.items.map(x=>({name:String(x.name||""),qty:Number(x.qty||0),price:Number(x.price||0)})):[]};const i=rows.findIndex(x=>String(x.id)===String(clean.id));if(i>=0)rows[i]=clean;else rows.unshift(clean);save(ORDERS,rows.slice(0,50000));const r=rangeFor('today'),summary=aggregate(rows,r.start,r.end);broadcast({type:"sales:update",summary});return json(res,200,{ok:true,summary})}catch(e){return json(res,400,{error:"bad request"})}}
 if(u.pathname==="/api/audit/sync"&&req.method==="POST"){if(!shop(req))return json(res,401,{error:"unauthorized"});try{const b=await body(req),a=b.audit;if(!a||!a.id)return json(res,400,{error:"missing audit"});const rows=load(AUDIT),i=rows.findIndex(x=>String(x.id)===String(a.id));if(i<0)rows.unshift(a);save(AUDIT,rows.slice(0,20000));return json(res,200,{ok:true})}catch(e){return json(res,400,{error:"bad request"})}}
 if(u.pathname==="/api/backup/snapshot"&&req.method==="POST"){if(!shop(req))return json(res,401,{error:"unauthorized"});try{const b=await body(req);save(BACKUP,b);return json(res,200,{ok:true,savedAt:new Date().toISOString()})}catch(e){return json(res,400,{error:"bad request"})}}
 if(u.pathname==="/api/dashboard/summary"&&req.method==="GET"){const type=["today","week","month","year"].includes(u.searchParams.get("range"))?u.searchParams.get("range"):"today",anchor=u.searchParams.get("date")||dateKey(),r=rangeFor(type,anchor);return json(res,200,{ok:true,range:type,summary:aggregate(load(ORDERS),r.start,r.end),serverTime:new Date().toISOString()})}
 if(u.pathname==="/api/dashboard/audit"&&req.method==="GET"){if(!dash(req,u))return json(res,401,{error:"unauthorized"});return json(res,200,{ok:true,rows:load(AUDIT).slice(0,100)})}
 if(u.pathname==="/api/line/test"&&req.method==="POST"){if(!shop(req))return json(res,401,{error:"unauthorized"});return json(res,200,await linePush("ทดสอบแจ้งเตือนจาก POS ร้านทิพย์เกษรเมี่ยงปลาเผา ✓"))}
 if(u.pathname==="/api/line/daily-summary"&&req.method==="POST"){if(!shop(req))return json(res,401,{error:"unauthorized"});return json(res,200,await linePush(dailyText()))}
 if(u.pathname==="/api/payment/callback"&&req.method==="POST")return json(res,501,{error:"payment_provider_not_configured",message:"Connect an approved merchant QR API/webhook and verify its signature before enabling automatic confirmation."});
 let p=u.pathname==="/"?"/remote-dashboard.html":u.pathname,target=path.normalize(path.join(ROOT,p));if(!target.startsWith(ROOT)){res.writeHead(403);return res.end("Forbidden")}fs.stat(target,(err,st)=>{if(err||!st.isFile()){res.writeHead(404);return res.end("Not found")}const ext=path.extname(target),mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".png":"image/png"}[ext]||"application/octet-stream";res.writeHead(200,{"Content-Type":mime,"Cache-Control":"no-cache"});fs.createReadStream(target).pipe(res)})});
const wss=new WebSocketServer({server,path:"/live"});wss.on("connection",ws=>{clients.add(ws);ws.on("close",()=>clients.delete(ws))});server.listen(PORT,"0.0.0.0",()=>console.log(`V65 cloud server listening on ${PORT}`));
setInterval(async()=>{if(!LINE_TOKEN||!LINE_TO)return;const p=bkkParts(),k=`${p.year}-${p.month}-${p.day}`;if(Number(p.hour)!==DAILY_HOUR||Number(p.minute)>4)return;let st=load(LINE_STATE);if(!st||Array.isArray(st))st={};if(st.lastDate===k)return;const r=await linePush(dailyText());if(r.ok){st.lastDate=k;save(LINE_STATE,st)}},60000);
